site_name: Guia de Addons de Minecraft
site_description: Documentação do zero ao avançado para criação de addons.
site_author: Natjllx

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para tema escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Mudar para tema claro
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - Aprender:
    - Início:
      - Introdução: index.md
      - Configuração: aprender/inicio/configuracao.md
      - Estrutura: aprender/inicio/estrutura.md
    - Dominando o JSON:
      - O que é JSON: aprender/json/conceito.md
      - Criando Itens: aprender/json/itens.md
      - Criando Blocos: aprender/json/blocos.md
    - Módulo Intermediário:
      - Modificando Mobs: aprender/intermediario/mobs.md
      - Tabelas de Drops: aprender/intermediario/drops.md
    - Módulo Avançado (Scripts):
      - Introdução ao GameTest: aprender/avancado/gametest.md
      - Criando Eventos: aprender/avancado/eventos.md
