site_name: Guia de Addons de Minecraft
site_description: Documentação do zero ao avançado para criação de addons.
site_author: Natjllx

theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - O COMEÇO:
    - index.md
    - O que é um Addon?: comecar/o-que-e.md
    - Requisitos & Instalação: comecar/instalacao.md
    - Seu Primeiro Addon: comecar/primeiro-addon.md
    - Estrutura de Pastas: comecar/estrutura.md
